export default {
  login: "OdiriTeddie",
  id: 41877178,
  node_id: "MDQ6VXNlcjQxODc3MTc4",
  avatar_url: "https://avatars.githubusercontent.com/u/41877178?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/OdiriTeddie",
  html_url: "https://github.com/OdiriTeddie",
  followers_url: "https://api.github.com/users/OdiriTeddie/followers",
  following_url:
    "https://api.github.com/users/OdiriTeddie/following{/other_user}",
  gists_url: "https://api.github.com/users/OdiriTeddie/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/OdiriTeddie/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/OdiriTeddie/subscriptions",
  organizations_url: "https://api.github.com/users/OdiriTeddie/orgs",
  repos_url: "https://api.github.com/users/OdiriTeddie/repos",
  events_url: "https://api.github.com/users/OdiriTeddie/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/OdiriTeddie/received_events",
  type: "User",
  site_admin: false,
  name: "Odiri Teddie",
  company: "Atop Web",
  blog: "odiriteddie.dev",
  location: "United Kingdom",
  email: null,
  hireable: true,
  bio: "Hi, I’m Teddie, a Front-End Engineer  who loves building digital products. ",
  twitter_username: "KingTeddie01",
  public_repos: 96,
  public_gists: 2,
  followers: 5,
  following: 10,
  created_at: "2018-07-29T20:33:39Z",
  updated_at: "2023-08-01T01:51:15Z",
};
